name: Deploy MultiDocker Application
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t 7688kuldeepsingh/react-test-up -f ./client/Dockerfile.dev ./client 
            - run: docker run -e CI=true 7688kuldeepsingh/react-test-up npm test -- --coverage --watchAll=false
            
            - run: docker build -t 7688kuldeepsingh/multi-client-up ./client
            - run: docker build -t 7688kuldeepsingh/multi-nginx-up ./nginx
            - run: docker build -t 7688kuldeepsingh/multi-server-up ./server
            - run: docker build -t 7688kuldeepsingh/multi-worker-up ./worker

            - run: docker push 7688kuldeepsingh/multi-client-up
            - run: docker push 7688kuldeepsingh/multi-nginx-up
            - run: docker push 7688kuldeepsingh/multi-server-up
            - run: docker push 7688kuldeepsingh/multi-worker-up